version: "2.1"
services:
  portainer:
    image: outlovecn/portainer-cn:latest
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
      - "8000:8000"
    volumes:
      - ./dockerconfig/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
