version: '3.1'

services:
  portainer-agent:
    image: portainer/agent:2.11.0
    restart: always
    ports:
      - 9000:9000
      - 8080:8080
      - 9443:9443
      
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
